[package]
name = "filesystem"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
common = { path = "../common" }
disk = { path = "../disk" }
uuid = { workspace = true }
operatingsystem = { path = "../operatingsystem" }
specs = { path = "../specs" }