[package]
name = "filesystem"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
disk = { path = "../disk" }
uuid = { version = "1.11.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
operatingsystem = { path = "../operatingsystem" }