[package]
name = "hwspec"
version = "0.1.0"
edition = "2024"

[dependencies]
byte-unit = { workspace = true }
config = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }