[workspace]
members = [ "cli", "core","disk", "downloader", "filesystem", "manifest", "operatingsystem",]
resolver = "2"

[workspace.dependencies]
attohttpc = { version = "0.28.2", features=["tls-native-vendored"] }
chrono = "0.4.38"
clap = { version = "4.5.21", features = ["derive"] }
ftp = "3.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
sha2 = "0.10.8"
tempfile = "3.12.0"
url = "2.5.4"
uuid = { version = "1.11.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
zip = "2.2.2"