[workspace]
members = [ "cli", "core","disk", "filesystem", "hwspec", "manifest", "operatingsystem",]
resolver = "2"

[workspace.dependencies]
attohttpc = { version = "0.29", features=["tls-native-vendored"] }
chrono = "0.4.40"
clap = { version = "4.5.28", features = ["derive"] }
config = { version = "0.15", features = ["toml"] }
crc32fast = { version = "1.4" }
directories = { version = "6.0.0" }
ftp = "3.0.1"
log = "0.4"
regex = "1"
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.34"
sha2 = "0.10.8"
tempfile = "3"
url = "2.5.4"
uuid = { version = "1.13.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
walkdir = { version = "2.5.0" }
zip = "2.6"
