version = 1

[metadata]
application = "DONKEY.BAS"
developer = "Microsoft"
genres = ["driving"]
year = "1981"

[hardware]
graphics = ["cga"]
sound = ["bleeper"]

[layers.hgcibm_11]
comment = "CGA emulator for Hercules Monochrome cards."
graphics = ["hercules"]
provides_graphics = ["cga"]
autoexec_bat_lines = ["HCGIBM.COM"]
min_dos = "1.00"
max_dos = "6.22"
dos_vendors = ["ibm"]
url = "https://dosk8s-dist.area536.com/hgcibm_11.zip"
checksum = "78173d19c1f7d96a6cf4ec711cd0d5d3301561b9cdef7875f7ad48368139f12c"

[layers.basica100]
comment = "IBM Disk BASIC interpreter"
checksum = "96cae63dc9f3eace501413598940d8a7f5ac6c84d5b7b59521c92fc936f88d93"
min_dos = "1.00"
max_dos = "1.00"
dos_vendors = ["ibm"]
url = "https://dosk8s-dist.area536.com/basica_100.zip"

[layers.donkey100]
comment = "DONKEY.BAS early demonstration of BASIC programming on IBM PC."
graphics = ["cga"]
url = "https://dosk8s-dist.area536.com/donkey_100.zip"
checksum = "4f9bb6eecd3c37d3034cf7f8fdb4f6ccfef2fcac3b3cf053b449860493e92b15"
min_dos = "1.00"
max_dos = "1.00"
dos_vendors = ["ibm"]
