[package]
name = "planner"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
common = { path = "../common" }
disk = { path = "../disk" }
filesystem = { path = "../filesystem" }
specs = { path = "../specs" }
operatingsystem = { path = "../operatingsystem" }