[package]
name = "disk"
version = "0.2.0"
edition = "2021"
description = "DOSContainer disk management library."
authors = ["Bas v.d. Wiel <bas@area536.com>"]

[dependencies]
common = { path = "../common" }

[dev-dependencies]
tempfile = { workspace = true }