[package]
name = "manifest"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { workspace = true }
directories = { workspace = true }
url = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
walkdir = { workspace = true }
