#[derive(Debug, PartialEq)]
pub enum FileSystemError {
    CannotAddParentlessEntry,
    CannotCreateDotfiles,
    ClusterAlreadyAllocated,
    ClusterNotUsable,
    ClusterOutOfBounds,
    DuplicateEntry,
    EntryCannotHaveChildren,
    EmptyFileName,
    ExtensionTooLong,
    FatSizeTooLarge,
    FileNameTooLong,
    InvalidCharInExt,
    InvalidCharInName,
    InvalidClusterIndex,
    InvalidPath,
    NotEnoughFreeClusters,
    ParentNotFound,
    TooManyFileNameParts,
    WontShrinkAllocationTable,
}
