[package]
name = "operatingsystem"
version = "0.1.14"
edition = "2021"
description = "DOSContainer operating system library."

[dependencies]
disk = { path = "../disk" }
serde = { workspace = true }
url = { workspace = true }