[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
disk = { path = "../disk" }
operatingsystem = { path = "../operatingsystem" }
specs = { path = "../specs" }
planner = { path = "../planner" }